export const formData = [
  {
    type: 'text',
    label: 'Name',
    name: 'name',
    placeholder: 'Enter your name',
    validators: { required: true, minlength: 3 },
  },
  {
    type: 'text',
    label: 'username',
    name: 'username',
    placeholder: 'Enter your name',
    validators: { required: true, minlength: 3 },
  },
  {
    type: 'text',
    label: 'first name',
    name: 'firstName',
    placeholder: 'Enter your name',
    validators: { required: true, minlength: 3 },
  },
  {
    type: 'text',
    label: 'last name',
    name: 'lastName',
    placeholder: 'Enter your name',
    validators: { required: true, minlength: 3 },
  },
  {
    type: 'email',
    label: 'Email',
    name: 'email',
    placeholder: 'Enter your email',
    validators: { required: true },
  },
  {
    type: 'number',
    label: 'Age',
    name: 'age',
    placeholder: 'Enter your age',
    validators: { required: true, min: 18 },
  },
  {
    type: 'select',
    label: 'Country',
    name: 'country',
    options: ['USA', 'Canada', 'UK'],
    validators: { required: true },
  },
  {
    type: 'select',
    label: 'Education',
    name: 'education',
    options: ['BCS', 'BCA', '12th', 'BE', 'B-tech'],
    validators: { required: true },
  },
  {
    type: 'checkbox',
    label: 'Accept Terms',
    name: 'terms',
    validators: { required: true },
  },
  {
    type: 'group',
    label: 'Address',
    name: 'address',
    fields: [
      {
        type: 'text',
        label: 'Street',
        name: 'street',
        placeholder: 'Enter your street',
        validators: { required: true },
      },
      {
        type: 'text',
        label: 'City',
        name: 'city',
        placeholder: 'Enter your city',
        validators: { required: true },
      },
      {
        type: 'number',
        label: 'Zip Code',
        name: 'zip',
        placeholder: 'Enter your zip code',
        validators: { required: true, minlength: 5 },
      },
    ],
  },
];
